### PR TITLE
Murisi/lists3

### PR DESCRIPTION
**Pull request by murisi**
Added support for lists and iteration to Vamp-IR in order to reduce the need for manually unrolling logic. More specifically, the changes are as follows:
* Added list constructors and patterns (`:` for cons and `[]` for nil) and modified the parser, pretty-printer, and type checker accordingly.
* Added an intrinsic function named `iter : Int -> (a -> a) -> (a -> a)` that applies a supplied function the given number of times.
* Modified the `alu.pir` test to start using the new list type and iteration function. The `range` definition is now much more concise and general.

Probably syntactic sugar could be added for iteration, but maybe that can be done in a separate pull request (which would probably still compile down to `iter`).

### CODE REVIEW

**Comment by AHartNtkn** [comment]
I tried out your list functions, and they do appear to work as intended. The only blemish I noticed during testing is that `iter` gives a rather opaque error when provided with a negative iterator. 

I'm not convinced about the design, though. It seems like adding case expressions and recursive types+folds might be something better in the long run. If that's too much for VampIR's minimalist ideals, then why add lists at all when lambda-encoded lists are already possible? Perhaps those questions have already been addressed; I'm not sure how much that's been discussed before I got here, so I'm not really equipped to confidently give approval or disapproval.

**Comment by murisi** [comment]
> I tried out your list functions, and they do appear to work as intended. The only blemish I noticed during testing is that `iter` gives a rather opaque error when provided with a negative iterator.
> 
> I'm not convinced about the design, though. It seems like adding case expressions and recursive types+folds might be something better in the long run. If that's too much for VampIR's minimalist ideals, then why add lists at all when lambda-encoded lists are already possible? Perhaps those questions have already been addressed; I'm not sure how much that's been discussed before I got here, so I'm not really equipped to confidently give approval or disapproval.

Thanks for testing the branch out! This approach is debatable and you bring up some good points:

1) Case expressions are certainly a possibility, but one of their drawbacks is that they compile inefficiently to arithmetic circuits in the general case, like if a user tried branching on a number. (See Figure 1 of https://cs.nyu.edu/~mwalfish/papers/buffet-ndss15.pdf ). With unrestricted case expressions, users might struggle to predict the efficiency of their program's output circuit.
2) User-definable recursive types plus folds minus case expressions would be a nice generalization of this PR (which only provides the list recursive type and its associated fold) that avoids the potential issues in (1). Charity, a total programming language, does this by automatically defining a fold for each data type (see http://pll.cpsc.ucalgary.ca/charity1/download/literature/manuals/manual.ps page 2). This approach is possible, but after custom data types I wonder how much VAMPIR would end up overlapping with GEB and Juvix?
3) Agreed, lambda-encoded lists are already possible. I did try implementing a general `range` function using by using Church numerals to repeat/iterate the list `tail` function on a list, but the type checker's occurs check rejected this because infinite types are not supported. Is there a list encoding that avoids this issue? Otherwise this lambda-encoding approach seems to require infinite types (or something else) to be added to the language which, while straightforward to implement, may have usability drawbacks.

**Comment by AHartNtkn** [comment]
Thanks for responding! 

1. I don't think that's relevant. We're talking about branching *during* circuit generation, not arithmetizing branching programs. So pattern matching would only occur at data types, it wouldn't touch field elements. This can already be emulated to some extent by lambda encodings.

```
// Bools
def CTrue x y = x;
def CFalse x y = y;

CTrue 0 1 = 0;

// Coproduct
def inl x l r = l x;
def inr x l r = r x;

def isZero x = {
  def xi = fresh (1|x);
  x * (1 - xi * x) = 0;
  1 - xi * x
};
def isEqual x y = isZero (x - y);
def coprodEq eq c1 c2 = 
  c1 (fun x {c2 (fun y { eq x y }) (fun y { 0 })})
     (fun x {c2 (fun y { 0 }) (fun y { eq x y })});
     
def c1 = inl 1;
def c2 = inl 2;
def c3 = inr 1;

coprodEq isEqual c1 c1 = 1;
coprodEq isEqual c1 c2 = 0;
coprodEq isEqual c1 c3 = 0;
```

These represent branching programs, but the branches themselves shouldn't effect the final circuit (at least in theory, I think it sometimes produces redundant public witnesses, but I'm not sure how that's controlled).

2. I agree. I'm not some kind of vision leader in the project, but I do know VampIR is supposed to be pretty minimal.

3. We can encode lists as their own folds via the type `forall X. X -> (A -> X -> X) -> X`. This doesn't require recursive types, and we can implement range w/ church numerals as you suggested

```
// Church Numerals
def zero z s = z;
def succ n z s = s (n z s);
def add n m z s = n (m z s) s;
def mul n m z s = n z (fun x {m x s});

def one = succ zero;
def two = add one one;
def four = mul two two;
def eight = add four four;
def ten = add two eight;

def to_int n = n 0 (fun x {1 + x});
to_int ten = 10;

// Lists
def nil n c = n;
def cons x xs n c = c x (xs n c);

def ex_list = cons 1 (cons 2 (cons 3 nil));

def sum l = l 0 (fun x y {x + y});
sum ex_list = 6;

def map f l n c = l n (fun x xs { c (f x) xs });
def range n = n nil (fun x { cons 0 (map (fun z {1+z}) x) });

// Testing
def rotate_10 (x0, x1, x2, x3, x4, x5, x6, x7, x8, x9) = 
  (x9, x0, x1, x2, x3, x4, x5, x6, x7, x8);
def replaceFst a (x, y) = (a, y);
def list2tup_10 l = 
  l (0, 0, 0, 0, 0, 0, 0, 0, 0, 0) 
    (fun x xs {replaceFst x (rotate_10 xs)});

list2tup_10 (range ten) = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
```

**Comment by murisi** [comment]
Hi!
1) I completely agree that branching can be implemented efficiently for values known at compile time. The compiler would "macro expand" until only arithmetic constraints are left. I had been thinking more about the UX of a `case` expression to vamp-ir users, since the `case` statement of other languages like Haskell often make no distinction between values known at compile-time and those not. If we started making a distinction, could it be awkward/unintuitive for vamp-ir users? To this end, I like how they do branching in Charity without really having a general `case` expression.
3) I had been thinking about the `range` function from `tests/alu.pir` (which constrains a number `x` to have `n` bits). But I just rechecked and realized that the compiler successfully type-checked and compiled a Church-encoding based version of this function. The problems that were actually preventing `tests/alu.pir` (of this branch) arose from trying to compile `nth`, a function that extracts the nth (encoded as a Church numeral) element of a list (also encoded as a Church numeral). I've extracted the failing part below:
```
def nil c n = n;
def cons h t c n = c h (t c n);
def hd l = l (fun h t { h }) nil;
def tl l c n = l (fun h t g { g h (t c) }) (fun t { n }) (fun h t { t });
def fold l f acc = l f acc;
def nth lst n = hd (n tl lst);
def two f x = f (f x);
def mylist = cons 2 (cons 9 (cons 1 (cons 5 nil)));
nth mylist two;
```
Infinite types could definitely make the above compile as-is (I just checked in Ocaml with `-rectypes`), but I wonder if there is a way to rewrite `nth` that doesn't involve this? More generally I see that many functions in `tests/alu.pir` (of this branch) continue compiling when `:` is replaced by `cons` and `[]` by `nil`, do you think Church encoding will work for every function in the file?

**Comment by AHartNtkn** [comment]
1. It seems to me that understanding the difference between compile-time computations and run-time is necessary to use VampIR anyway. It appears in how exponential work (requiring only constants in the exponent), in how your iter function works, and broadly it seems necessary to understand that, for example, the length of a tuple can't vary based on field element values. Maybe it's unintuitive, but that doesn't matter if it's necessary. I'll have to look at Charity; I'm unfamiliar with it.
2. Hmm... there seems to be two problems with that implementation. The first is that `hd` isn't type safe; its trying to return something that's both a list and an element of a list, which doesn't make sense in general. This can easily be fixed by having it return a maybe;
```
def nothing n j = n;
def just x n j = j x;
def hd l n j = l (fun x xs {j x}) n;
```
however, the bigger issue is the tail function. This *does not* require recursive types; but it also can't be simply typed. It can be typed using rank-2 types. For example, in Haskell, this would be
```
{-# LANGUAGE Rank2Types #-}

newtype List a = 
    List { runList :: forall r. (a -> r -> r) -> r -> r }

ctail :: List a -> List a
ctail l = List (\c n -> runList l (\h t g ->  g h (t c) ) (\t -> n) (\h t -> t))

church2 = \f x -> f (f x)
test = church2 ctail
```
So, while recursive types are not necessary, it doesn't seem that the current type system is sufficient anyway. This suggests several different extensions (or, perhaps, stripping out most of the type system and only caring about normalization at compile-time). This warrants further discussion elsewhere.

**Review by lopeetall — APPROVED** [review]
Approved, with the expectation that we continue thinking about the discussion started here

**Pull request merged**
