### PR TITLE
Carlo/halo2 pi

### PR DESCRIPTION
**Pull request by CarloModicaPortfolio**

### CODE REVIEW

**Comment by AHartNtkn** [comment]
I looked through your code and tested it myself, and everything seems fine, but I can't tell what differences in behavior there are. Does this change how Vamp-IR behaves? Does this just pipe public inputs into the instance columns during halo2 proof creation?

**Comment by CarloModicaPortfolio** [comment]
Before this modification Vamp-IR, when used with halo2 as a backend, was not handling public inputs correctly, as it was treating all inputs as private. So now it is treating public variables as they should, filling the instances column. More so, the prover returns together with the proof also the serilized public inputs to the verifier, which without them could not verify the proof

**Comment by lopeetall** [comment]
can @XuyangSong or @bazzilic test this out and see if it solves the issue?

**Review by XuyangSong — APPROVED** [review]
Thanks. I've tested it. It looks good. 
I found you added a gate and a copy to handle the public input. Could we just use the underlying `constrain_instance` function in Halo2 to publicize the variables?

**Comment by bazzilic** [comment]
LGTM apart from @XuyangSong 's concern about `constrain_instance` ☝️
Also, it might be useful if inputs are not packed into the same file with proof and are instead a separate JSON file.

**Review by bazzilic — APPROVED** [review]

**Review by AHartNtkn — APPROVED** [review]
Since it all looks good, I'll merge it. Those suggestions should be turned into issues with the "enhancement" label.

**Pull request merged**
